apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: testapp 
spec:
  selector:
    matchLabels:
      app: testapp
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp 
    spec:
      containers:
        - name: testapp 
          image: testcr.azurecr.io/testapp
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testservice
spec:
  selector:
    app: testapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: testingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          serviceName: testservice
          servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testconfigmap
data:
  # property-like keys; each key maps to a simple value
  whats_this: "testing"
  why_this: "testing"
---
apiVersion: v1
kind: Service
metadata:
  name: testservice-2
spec:
  selector:
    app: testapp-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: testingress-1
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          serviceName: testnotservice
          servicePort: 80
---