apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: testapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp 
    spec:
      containers:
        - name: testapp 
          image: testcr.azurecr.io/testapp
          ports:
          - containerPort: 80