name: Bug Report
description: File a bug report, we will respond to this thread with any questions.
title: 'Bug: '
labels: ['bug', 'triage']
assignees: '@Azure/aks-atlanta'
body:
   - type: input
     id: What-happened
     attributes:
        label: What happened?
        description: Tell us what did you expect to happen?
        placeholder: Tell us what you see!
     validations:
        required: true
   - type: input
     id: Runner
     attributes:
        label: Runner
        description: What runner are you using?
        placeholder: Mention the runner info (self-hosted, operating system)
     validations:
        required: true
   - type: input
     id: Logs
     attributes:
        label: Relevant log output
        description: Run in debug mode for the most verbose logs. Please feel free to attach a screenshot of the logs
        render: shell
