blank_issues_enabled: false
contact_links:
   - name: GitHub Action "k8s-deploy" Support
     url: https://github.com/Azure/k8s-deploy
     security: https://github.com/Azure/k8s-deploy/blob/main/SECURITY.md
     about: Please ask and answer questions here.
