blank_issues_enabled: false
contact_links:
   - name: GitHub Action "k8s-create-secret" Support
     url: https://github.com/Azure/k8s-create-secret
     security: https://github.com/Azure/k8s-create-secret/blob/main/SECURITY.md
     about: Please ask and answer questions here.
