name: Feature Request
description: File a Feature Request form, we will respond to this thread with any questions.
title: 'Feature Request: '
labels: ['Feature']
assignees: '@Azure/aks-atlanta'
body:
   - type: textarea
     id: Feature_request
     attributes:
        label: Feature request
        description: Provide example functionality and links to relevant docs
     validations:
        required: true
