name: release Project

on:
   push:
      branches:
         - main
      paths:
         - CHANGELOG.md
   workflow_dispatch:

jobs:
   release:
      uses: Azure/action-release-workflows/.github/workflows/release_js_project.yaml@12e20b8
      with:
         changelogPath: ./CHANGELOG.md
