name: Release Project

on:
   push:
      branches:
         - main
      paths:
         - CHANGELOG.md
   workflow_dispatch:

jobs:
   release:
      permissions:
         actions: read
         contents: write
      uses: Azure/action-release-workflows/.github/workflows/release_js_project.yaml@a391b701462581f586d0e8a68e60b04aa47dc4a9 # v1.2.0
      with:
         changelogPath: ./CHANGELOG.md
