name: Release Project

on:
   push:
      branches:
         - main
      paths:
         - CHANGELOG.md
   workflow_dispatch:

jobs:
   release:
      permissions:
         actions: read
         contents: write
      uses: Azure/action-release-workflows/.github/workflows/release_js_project.yaml@2ff084415c5af591fd13d95ddbfc4cdb5ed2012e # v1.1.0
      with:
         changelogPath: ./CHANGELOG.md
