name: release Project

on:
   push:
      branches:
         - main
      paths:
         - CHANGELOG.md
   workflow_dispatch:

jobs:
   release:
      uses: Azure/action-release-workflows/.github/workflows/release_js_project.yaml@12e20b89e7822d372714b84a7a844ba88fb1bbf0
      with:
         changelogPath: ./CHANGELOG.md
